classifier_name: baseline
classifier_loss_fn: cce
classifier_classes:
  - anger
  - disgust
  - fear
  - joy
  - neutral
  - sadness
  - surprise

modules_text_encoder: glove
modules_visual_encoder: resnet50
modules_audio_encoder: waveform
modules_fusion: concat

text_in_features: 50
text_out_features: 50

audio_in_features: 150000 # truncates the waveform afeter 150K samples
audio_out_features: 32

visual_in_features: 546816 # 256 x 721 x 3 (RGB)
visual_out_features: -1 # defined automatically by resnet50

feedforward_layers:
  - out_features: 512
    dropout: 0.2
  - out_features: 32
    dropout: 0
