classifier_name: baseline
classifier_loss_fn: cce
classifier_classes:
  - anger
  - disgust
  - fear
  - joy
  - neutral
  - sadness
  - surprise

modules_text_encoder: glove
modules_visual_encoder: resnet50
modules_audio_encoder: waveform
modules_fusion: concat

text_in_features: 300
text_out_features: 300

audio_in_features: 300000 # truncates the waveform after 300K samples
audio_out_features: 256

visual_in_features: [3, 256, 721] # input required for resnet50
visual_out_features: -1 # defined automatically by resnet50

feedforward_layers:
  - out_features: 2048
    dropout: 0.2
  - out_features: 512
    dropout: 0.2
  - out_features: 128
    dropout: 0.2
  - out_features: 32
    dropout: 0.2
