classifier_name: e01-gpt2
classifier_loss_fn: cce
classifier_learning_rate: 0.00001
classifier_weight_decay: 0.1
classifier_warmup_steps: 5
classifier_classes:
  - anger
  - disgust
  - fear
  - joy
  - neutral
  - sadness
  - surprise

modules_text_encoder: gpt2
modules_visual_encoder: resnet50
modules_audio_encoder: waveform
modules_fusion: concat

text_in_features: -1 # defined by tokenizer & padding
text_out_features: -1 # defined by the encoder output hidden state

audio_in_features: 150000 # truncates the waveform after 150K samples
audio_out_features: 32

visual_in_features: [3, 256, 721] # input required for resnet50
visual_out_features: -1 # defined automatically by resnet50

feedforward_layers:
  - out_features: 512
    dropout: 0.2
  - out_features: 32
    dropout: 0
