classifier_name: final-i01-waveform-150Kx50
classifier_loss_fn: dice
classifier_learning_rate: 0.00005
classifier_weight_decay: 0.1
classifier_warmup_steps: 1000 # @ ~15% => 9989 (examples) / 16 (batch) = 625 (step) x 10 (epochs) = 6250 steps
classifier_metric_for_best_model: f1_weighted
classifier_early_stopping_patience: 5
classifier_classes:
  - anger
  - disgust
  - fear
  - joy
  - neutral
  - sadness
  - surprise

modules_text_encoder: gpt2
modules_visual_encoder: resnet50
modules_audio_encoder: waveform
modules_fusion: multi_headed_attn

text_in_features: -1 # defined by tokenizer & padding
text_out_features: -1 # defined by the encoder output hidden state

audio_in_features: 150000 # truncates the waveform after 150K samples
audio_out_features: 50

fusion_out_features: 512
fusion_attention_heads_degree: 3 # for 512, degree 3 = 4 heads

feedforward_layers:
  - out_features: 256
    dropout: 0.2
  - out_features: 128
    dropout: 0.2
