classifier_name: mock
classifier_loss_fn: cce
classifier_learning_rate: 0.00005
classifier_weight_decay: 0.1
classifier_warmup_steps: 4
classifier_metric_for_best_model: f1_weighted
classifier_early_stopping_patience: 1
classifier_classes:
  - fear
  - neutral
  - sadness
  - surprise

modules_text_encoder: glove
modules_visual_encoder: resnet50
modules_audio_encoder: waveform
modules_fusion: concat

text_in_features: 50
text_out_features: 50

audio_in_features: 150000 # truncates the waveform after 150K samples
audio_out_features: 32

visual_in_features: [3, 256, 721] # input required for resnet50
visual_out_features: -1 # defined automatically by resnet50

feedforward_l2norm: true
feedforward_layers:
  - out_features: 64
    dropout: 0.2
  - out_features: 32
    dropout: 0
