classifier_name: t-um-glove
classifier_loss_fn: dice
classifier_learning_rate: 0.00005
classifier_weight_decay: 0.1
classifier_warmup_steps: 250 # @ ~15% => 9989 (examples) / 64 (batch) = 157 (step) x 10 (epochs) = 1570 steps
classifier_metric_for_best_model: f1_weighted
classifier_early_stopping_patience: 5
classifier_classes:
  - anger
  - disgust
  - fear
  - joy
  - neutral
  - sadness
  - surprise

modules_text_encoder: glove
modules_visual_encoder: none
modules_audio_encoder: none
modules_fusion: concat

text_in_features: 50 # smallest GloVe
text_out_features: 50 # smallest GloVe

feedforward_layers:
  - out_features: 256
    dropout: 0.2
